AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DATAINICIO:
    Type: String
  DATAFIM:
    Type: String
  BUCKETINGESTAO:
    Type: String
  ITENSPAGINA:
    Type: String
  LambdaBucket:
    Type: String
Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: dataingestion
      Handler: index.handler
      Role: arn:aws:iam::885248014373:role/service-role/DataIn-role-f0nn8cop
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: function.zip
      Runtime: python3.7
      Timeout: 10
      Environment:
        Variables:
          DATA_INICIO: !Ref DATAINICIO
          DATA_FIM: !Ref DATAFIM
          BUCKET_INGESTAO: !Ref BUCKETINGESTAO
          ITENS_PAGINA: !Ref ITENSPAGINA
  Scheduler:
    Type: AWS::Events::Rule
    Properties: 
      EventBusName: default
      Name: Hardin-Data-Ingestion-Scheduler
      ScheduleExpression: "rate(1 day)"
      State: ENABLED
      Targets: 
        - 
          Arn: !GetAtt Function.Arn
          Id: Hardin-Data-Ingestion-Target
  SchedulerInvokePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref Function
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt Scheduler.Arn


  
      
  
   
    
