name: Data Ingestion Lambda Function
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from your account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Data Ingestion Lambda Function
        run: | 
          zip lambda_function.py function.zip \
          aws s3api create-bucket \
            --bucket data-ingestion-source \
            --region us-east-1 \          
          aws s3api put-object \
            --bucket data-ingestion-source \
            --key function.zip \
            --region us-east-1 \
            --body function.zip \
          aws cloudformation deploy \
            --stack-name cloud-atlas-lambda-data-ingestion \
            --template-file template.yaml \
            --parameter-overrides file://parameters.json
            